const state={running:false,paused:false,live:false,connected:false,price:4288.42,balance:1000,equity:1000,positions:[],orders:[],logs:[],cfg:{initialLot:.01,gridStep:10,multiplier:1.5,maxLevels:10,maxLot:.5,maxDrawdown:10,maxMargin:50,basketTarget:5},symbol:"XAUUSD",bridgeUrl:"",bridgeToken:""};
const $=id=>document.getElementById(id);
function log(msg,type="info"){state.logs.unshift({time:new Date().toLocaleTimeString(),msg,type});renderLogs()}
function money(n){return (n<0?"-":"")+"$"+Math.abs(Number(n)||0).toFixed(2)}
function render(){
  $("balance").textContent=money(state.balance);$("equity").textContent=money(state.equity);const fl=state.equity-state.balance;$("floating").textContent=money(fl);$("price").textContent=Number(state.price||0).toFixed(2);$("chartPrice").textContent=Number(state.price||0).toFixed(2);
  $("positionsCount").textContent=state.positions.length;$("ordersCount").textContent=state.orders.length;$("positionSummary").textContent=state.positions.length;$("orderSummary").textContent=state.orders.length;$("symbol").textContent=state.symbol;$("robotStatus").textContent=state.running?(state.paused?"PAUSED":"RUNNING"):"STOPPED";$("lots").textContent=state.positions.reduce((a,p)=>a+(Number(p.lot)||0),0).toFixed(2);$("basket").textContent=money(fl);
  const dd=Math.max(0,(state.balance-state.equity)/Math.max(1,state.balance)*100);$("drawdown").textContent=dd.toFixed(1)+"%";$("riskFill").style.width=Math.min(100,dd/state.cfg.maxDrawdown*100)+"%";$("marginUsage").textContent=state.marginUsage!=null?Number(state.marginUsage).toFixed(1)+"%":"—";$("maxDD").textContent=state.cfg.maxDrawdown.toFixed(1)+"%";
  $("connection").innerHTML=state.connected?"<i></i> MT5 CONNECTED":(state.live?"<i></i> BRIDGE ERROR":"<i></i> DEMO MODE");$("modeLabel").textContent=state.live?(state.connected?"LIVE MT5":"LIVE / OFFLINE"):"DEMO / SIMULATION";
  $("bridgeState").textContent=state.connected?"CONNECTED":"DISCONNECTED";$("account").textContent=state.account||"—";$("server").textContent=state.server||"—";
  renderGrid();renderLists();renderSim()
}
function renderGrid(){let lev="";for(let i=1;i<=state.cfg.maxLevels;i++){const d=i*state.cfg.gridStep;const lot=Math.min(state.cfg.maxLot,state.cfg.initialLot*Math.pow(state.cfg.multiplier,i-1));lev+=`<div class="level" style="top:${Math.min(94,i*7)}%"><span>L${i} · ${d.toFixed(1)} USD</span><b>${lot.toFixed(2)} lot</b></div>`}$('levels').innerHTML=lev;const rows=[];for(let i=1;i<=state.cfg.maxLevels;i++)rows.push(`<div class="listrow"><span>L${i}</span><span>${Math.min(state.cfg.maxLot,state.cfg.initialLot*Math.pow(state.cfg.multiplier,i-1)).toFixed(2)} lot</span><span>${(state.price-i*state.cfg.gridStep).toFixed(2)}</span></div>`);$('buyTable').innerHTML=rows.slice(0,Math.min(8,state.cfg.maxLevels)).join('');$('sellTable').innerHTML=rows.slice(0,Math.min(8,state.cfg.maxLevels)).map((x,i)=>x.replace((state.price-(i+1)*state.cfg.gridStep).toFixed(2),(state.price+(i+1)*state.cfg.gridStep).toFixed(2))).join('');$('buyGrid').textContent=state.positions.filter(p=>p.type==='BUY').length?'L'+state.positions.filter(p=>p.type==='BUY').length:'L0';$('sellGrid').textContent=state.positions.filter(p=>p.type==='SELL').length?'L'+state.positions.filter(p=>p.type==='SELL').length:'L0'}
function renderLists(){$('positionsList').innerHTML=state.positions.length?state.positions.map(p=>`<div class="listrow"><span><b>${p.type}</b><br><small>${state.symbol} · L${p.level??'—'}</small></span><span>${Number(p.lot).toFixed(2)} lot<br><small>${Number(p.entry).toFixed(2)}</small></span><b>${money(p.pl)}</b></div>`).join(''):"<div class='listrow'>No open positions.</div>";$('ordersList').innerHTML=state.orders.length?state.orders.map(o=>`<div class="listrow"><span><b>${o.type}</b><br><small>${state.symbol} · L${o.level??'—'}</small></span><span>${Number(o.lot).toFixed(2)} lot<br><small>${Number(o.price).toFixed(2)}</small></span><span class="tag">PENDING</span></div>`).join(''):"<div class='listrow'>No pending orders.</div>"}
function renderSim(){let h="";for(let i=1;i<=state.cfg.maxLevels;i++){let lot=Math.min(state.cfg.maxLot,state.cfg.initialLot*Math.pow(state.cfg.multiplier,i-1));h+=`<div class="listrow"><span>Level ${i}</span><span>${lot.toFixed(2)} lot</span><b>${money(lot*state.cfg.gridStep*100)}</b></div>`}$('simulation').innerHTML=h}
function renderLogs(){$('logsList').innerHTML=state.logs.map(l=>`<div class="log"><span>${l.time}</span> <b class="${l.type}">[${l.type.toUpperCase()}]</b> ${l.msg}</div>`).join('')||"<div class='log'>No logs yet.</div>"}
function setPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.page===id))}
async function bridge(path,method='GET',body=null){if(!state.bridgeUrl||!state.bridgeToken)throw new Error('Bridge URL and token are required');const r=await fetch(state.bridgeUrl.replace(/\/$/,'')+path,{method,headers:{'Content-Type':'application/json','X-Bridge-Token':state.bridgeToken},body:body?JSON.stringify(body):undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
async function sendCommand(type,config=null){try{const data=await bridge('/api/command','POST',{type,config});log(`Command ${type} accepted by bridge (ID ${data.command?.id||'—'}).`,'success');return true}catch(e){log(`Command ${type} failed: ${e.message}`,'error');return false}}
async function syncBridge(){if(!state.bridgeUrl||!state.bridgeToken)return;try{const d=await bridge('/api/status');state.connected=!!d.connected;state.live=state.connected;if(d.state){const s=d.state;state.balance=Number(s.balance??state.balance);state.equity=Number(s.equity??state.equity);state.price=Number(s.bid||s.ask||state.price);state.symbol=s.symbol||state.symbol;state.account=s.account?String(s.account):state.account;state.server=s.server||state.server;state.running=!!s.running;state.paused=!!s.paused;state.marginUsage=(Number(s.margin||0)/Math.max(0.01,Number(s.equity||1))*100)}render()}catch(e){state.connected=false;state.live=true;render()}}

document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>setPage(b.dataset.page));
$('startBtn').onclick=async()=>{if(state.connected){await sendCommand('START');return}state.running=true;state.paused=false;log('Robot started in DEMO mode.','success');render()};
$('pauseBtn').onclick=async()=>{if(state.connected){await sendCommand('PAUSE');return}state.paused=true;log('Robot paused. No new entries will be created.','warning');render()};
$('stopBtn').onclick=async()=>{if(state.connected){await sendCommand('STOP');return}state.running=false;state.paused=false;log('Robot stopped.','info');render()};
$('closeBtn').onclick=()=>$('modal').classList.remove('hidden');$('cancelModal').onclick=()=>$('modal').classList.add('hidden');$('confirmClose').onclick=async()=>{if(state.connected){await sendCommand('CLOSE_ALL')}else{state.positions=[];state.orders=[];state.equity=state.balance;state.running=false;log('Emergency close-all completed in DEMO mode.','success');render()}$('modal').classList.add('hidden')};
$('saveRisk').onclick=async()=>{['initialLot','gridStep','multiplier','maxLevels','maxLot','maxDrawdown','maxMargin','basketTarget'].forEach(k=>state.cfg[k]=Number($(k).value));if(state.connected)await sendCommand('CONFIG',state.cfg);else log('Risk/grid configuration saved locally for DEMO mode.','success');render()};
$('saveSymbol').onclick=()=>{state.symbol=$('detectedSymbol').value||'XAUUSD';log('Symbol configuration saved for '+state.symbol+'.','success');render()};
$('connectBridge').onclick=async()=>{state.bridgeUrl=$('bridgeUrl').value.trim();state.bridgeToken=$('bridgeToken').value.trim();if(!state.bridgeUrl||!state.bridgeToken){log('Enter the bridge HTTPS URL and pairing token.','warning');return}try{const d=await bridge('/api/status');state.connected=!!d.connected;state.live=true;if(!state.connected)log('Bridge reached, but the MT5 EA heartbeat is not online yet.','warning');else log('MT5 bridge and EA verified.','success');await syncBridge()}catch(e){state.connected=false;state.live=true;log('Bridge connection failed: '+e.message,'error');render()}};
$('disconnectBridge').onclick=()=>{state.connected=false;state.live=false;state.bridgeUrl='';state.bridgeToken='';log('MT5 bridge disconnected from this browser session.','info');render()};
setInterval(syncBridge,3000);
setInterval(()=>{if(!state.connected&&state.running&&!state.paused){state.price+=(Math.random()-.5)*1.8;state.equity=state.balance+(Math.random()-.5)*12;state.positions.forEach(p=>p.pl=(p.type==='BUY'?state.price-p.entry:p.entry-state.price)*p.lot*100);render()}},1200);
log('Demo provider initialized.','info');log('No live MT5 connection. Connect a persistent MT5 bridge/EA to enable execution.','warning');render();
